module HasPicList exposing (..)
pList : List String
pList = [ "arm wound"
     , "boots"
     , "canoe"
     , "dillinger"
     , "dysentery"
     , "elixer"
     , "exhaustion"
     , "horse"
     , "hunger"
     , "knife"
     , "leg wound"
     , "lump hammer"
     , "mallet"
     , "owie"
     , "pan"
     , "pickaxe"
     , "potion"
     , "revolver"
     , "rifle"
     , "saw"
     , "sledge hammer"
     , "stalion"
     , "thirst"
     , "trident"
    ]