module HasPicList exposing (..)
pList : List String
pList = [ "arm wound"
     , "axe"
     , "big pan"
     , "binoculars"
     , "boots"
     , "bow"
     , "canoe"
     , "climbing boots"
     , "cow"
     , "crossbow"
     , "dagger"
     , "dillinger"
     , "drill"
     , "dysentery"
     , "elixer"
     , "exhaustion"
     , "fishing rod"
     , "forager"
     , "gambler"
     , "horse"
     , "hunger"
     , "hunting knife"
     , "knife"
     , "leg wound"
     , "lump hammer"
     , "mallet"
     , "net"
     , "net2"
     , "owie"
     , "pan"
     , "pickaxe"
     , "potion"
     , "revolver"
     , "rifle"
     , "roaming trader"
     , "rookie trader"
     , "sailboat"
     , "saw"
     , "skilled trader"
     , "sledgehammer"
     , "stalion"
     , "sword"
     , "telescope"
     , "thirst"
     , "trader"
     , "trident"
     , "two man saw"
     , "wagon"
     , "whiskey"
    ]
cList : List String 
cList = [ "driftina wood"
    , "elisa watton"
    , "jake wilder"
    , "sam boater"
    , "wayne johns"
    ]